CREATE TABLE [dbo].[InProcLog] (
    [Date]                     DATE       NULL,
    [OnePhasePoleRepair]       FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhasePoleRepair] DEFAULT ((0)) NULL,
    [TotalPoleRepair]          FLOAT (53) CONSTRAINT [DF_InProcLog_TotalPoleRepair] DEFAULT ((0)) NULL,
    [PoleScrap]                FLOAT (53) CONSTRAINT [DF_InProcLog_PoleScrap] DEFAULT ((0)) NULL,
    [OnePhasePoleEst]          FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhasePoleEst] DEFAULT ((0)) NULL,
    [OnePhasePadRepair]        FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhasePadRepair] DEFAULT ((0)) NULL,
    [APCOPadRepair]            FLOAT (53) CONSTRAINT [DF_InProcLog_APCOPadRepair] DEFAULT ((0)) NULL,
    [OnePhasePadScrap]         FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhasePadScrap] DEFAULT ((0)) NULL,
    [ThreePhasePadRepair]      FLOAT (53) CONSTRAINT [DF_InProcLog_ThreePhasePadRepair] DEFAULT ((0)) NULL,
    [ThreePhasePadScrap]       FLOAT (53) CONSTRAINT [DF_InProcLog_ThreePhasePadScrap] DEFAULT ((0)) NULL,
    [RegulatorRepair]          FLOAT (53) CONSTRAINT [DF_InProcLog_RegulatorRepair] DEFAULT ((0)) NULL,
    [PanelRepair]              FLOAT (53) CONSTRAINT [DF_InProcLog_PanelRepair] DEFAULT ((0)) NULL,
    [PanelScrap]               FLOAT (53) CONSTRAINT [DF_InProcLog_PanelScrap] DEFAULT ((0)) NULL,
    [OnePhaseRecloserRepair]   FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhaseRecloserRepair] DEFAULT ((0)) NULL,
    [OnePhaseRecloserScrap]    FLOAT (53) CONSTRAINT [DF_InProcLog_OnePhaseRecloserScrap] DEFAULT ((0)) NULL,
    [ThreePhaseRecloserRepair] FLOAT (53) CONSTRAINT [DF_InProcLog_ThreePhaseRecloserRepair] DEFAULT ((0)) NULL,
    [ThreePhaseRecloserScrap]  FLOAT (53) CONSTRAINT [DF_InProcLog_ThreePhaseRecloserScrap] DEFAULT ((0)) NULL,
    [SGearRepair]              FLOAT (53) CONSTRAINT [DF_InProcLog_SGearRepair] DEFAULT ((0)) NULL,
    [KVARepair]                FLOAT (53) CONSTRAINT [DF_InProcLog_KVARepair] DEFAULT ((0)) NULL,
    [KVAScrap]                 FLOAT (53) CONSTRAINT [DF_InProcLog_KVAScrap] DEFAULT ((0)) NULL,
    [KVAKnownScrap]            FLOAT (53) CONSTRAINT [DF_InProcLog_KVAKnownScrap] DEFAULT ((0)) NULL,
    [APCOScrap]                FLOAT (53) CONSTRAINT [DF_InProcLog_APCOScrap] DEFAULT ((0)) NULL,
    [FourHConvert]             FLOAT (53) CONSTRAINT [DF_InProcLog_FourHConvert] DEFAULT ((0)) NULL,
    [InProcLogId]              INT        IDENTITY (1, 1) NOT NULL,
    [RegulatorScrap]           FLOAT (53) CONSTRAINT [[dbo]].[InProcLog]]RegulatorScrapDefault] DEFAULT ((0)) NULL,
    [APCORepair]               FLOAT (53) CONSTRAINT [[dbo]].[InProcLog]]APCORepairDefault] DEFAULT ((0)) NULL,
    [uLocation]                INT        NULL,
    CONSTRAINT [PK_InProcLog] PRIMARY KEY CLUSTERED ([InProcLogId] ASC)
);

