CREATE TABLE [dbo].[Inventories] (
    [LocationName]        VARCHAR (150) NULL,
    [Manufacturer]        VARCHAR (250) NULL,
    [Id]                  INT           NOT NULL,
    [Barcode]             VARCHAR (50)  NULL,
    [SerialNumber]        VARCHAR (50)  NULL,
    [Comments]            VARCHAR (500) NULL,
    [WEIGHT]              FLOAT (53)    NULL,
    [Impedance]           FLOAT (53)    NULL,
    [EOK]                 VARCHAR (3)   NULL,
    [Year]                INT           NULL,
    [InventoryLocationID] INT           NULL,
    [Status]              VARCHAR (15)  NULL,
    [SoldDate]            DATETIME      NULL,
    [DeComDate]           DATETIME      NULL,
    [SoldTo]              INT           NULL,
    [SoldtoJobNumber]     VARCHAR (50)  NULL,
    [Manifest]            VARCHAR (50)  NULL,
    [SoldToCust]          VARCHAR (150) NULL,
    [LocationID]          INT           NULL,
    [KVA]                 VARCHAR (150) NULL,
    [Amps]                VARCHAR (150) NULL,
    [LocationDetail]      VARCHAR (150) NULL,
    [Primary Voltage]     VARCHAR (150) NULL,
    [Secondary Voltage]   VARCHAR (150) NULL,
    [Job Type]            VARCHAR (150) NULL,
    [Taps]                VARCHAR (150) NULL,
    [Type]                VARCHAR (150) NULL,
    [LoopRadial]          VARCHAR (150) NULL,
    [Front]               VARCHAR (150) NULL,
    [TankType]            VARCHAR (150) NULL,
    [Repaired]            VARCHAR (150) NULL,
    [InventoryId]         VARCHAR (50)  NULL,
    [AccountedFor]        VARCHAR (5)   NULL,
    [DateScanned]         DATETIME      NULL,
    [LocationScanned]     VARCHAR (50)  NULL,
    [PrimaryWinding]      VARCHAR (150) NULL,
    [SecondaryWinding]    VARCHAR (150) NULL,
    [RepairedDate]        DATETIME      NULL,
    [PickupDate]          DATETIME      NULL
);

