CREATE TABLE [dbo].[Inventory] (
    [Id]                INT           IDENTITY (1, 1) NOT NULL,
    [Barcode]           VARCHAR (50)  NULL,
    [SerialNumber]      VARCHAR (50)  NULL,
    [Comments]          VARCHAR (500) NULL,
    [KVA]               FLOAT (53)    NULL,
    [AMPS]              FLOAT (53)    NULL,
    [WEIGHT]            FLOAT (53)    NULL,
    [Impedance]         FLOAT (53)    NULL,
    [JOB_TYPE]          INT           NULL,
    [LocationDetail]    VARCHAR (150) NULL,
    [PrimaryVoltage]    INT           NULL,
    [SecondaryVoltage]  INT           NULL,
    [Manufacturer]      INT           NULL,
    [TAPS]              INT           NULL,
    [TYPE]              INT           NULL,
    [LOOP_RAD]          INT           NULL,
    [FRONT]             INT           NULL,
    [EOK]               VARCHAR (3)   NULL,
    [Year]              INT           NULL,
    [InventoryLocation] INT           NULL,
    [TankType]          INT           NULL,
    [Repaired]          INT           NULL,
    [Status]            VARCHAR (15)  CONSTRAINT [DF_Inventory_Status] DEFAULT ('Inventory') NULL,
    [SoldTo]            INT           NULL,
    [SoldtoJobNumber]   VARCHAR (50)  NULL,
    [SoldDate]          DATETIME      NULL,
    [DeComDate]         DATETIME      NULL,
    [Manifest]          VARCHAR (50)  NULL,
    [CustomerNumber]    VARCHAR (50)  NULL,
    [PickupDate]        DATETIME      NULL,
    [Datestamp]         DATETIME      CONSTRAINT [[dbo]].[Inventory]]DatestampDefault] DEFAULT (getdate()) NULL,
    [fuse]              INT           NULL,
    [Condition]         INT           NULL,
    [Volts]             VARCHAR (50)  NULL,
    [W_PANEL_WITH]      VARCHAR (5)   NULL,
    [PANEL_SER]         VARCHAR (50)  NULL,
    [PrimaryWinding]    INT           NULL,
    [SecondaryWinding]  INT           NULL,
    [RepairedDate]      DATETIME      NULL
);

