CREATE TABLE [dbo].[NonPCBBermLog] (
    [BermLogId]         INT           IDENTITY (1, 1) NOT NULL,
    [BatchId]           INT           NULL,
    [Barcode]           VARCHAR (50)  NULL,
    [SerialNumber]      VARCHAR (50)  NULL,
    [InitialWeight]     FLOAT (53)    NULL,
    [CarcassWeight]     FLOAT (53)    NULL,
    [Gallons]           FLOAT (53)    NULL,
    [OilTankId]         INT           NULL,
    [PPM]               FLOAT (53)    NULL,
    [DateStamp]         DATETIME      NULL,
    [LastUpdated]       DATETIME      NULL,
    [SendTo]            VARCHAR (5)   NULL,
    [ContinuationGroup] INT           NULL,
    [PCBSampleId]       INT           NULL,
    [Drained]           VARCHAR (25)  NULL,
    [DateCompleted]     DATETIME      NULL,
    [ASD]               DATETIME      NULL,
    [SequenceNumber]    VARCHAR (25)  NULL,
    [PCBItemTypeID]     INT           NULL,
    [PumpOutDate]       DATE          NULL,
    [ManualEntry]       BIT           NULL,
    [ContinuationId]    INT           NULL,
    [KVA]               FLOAT (53)    NULL,
    [PickUpDate]        DATETIME      NULL,
    [CustomerNumber]    VARCHAR (50)  NULL,
    [Description]       VARCHAR (150) NULL,
    [acsinfo]           BIT           NULL,
    [OilContinuationId] INT           NULL,
    [DoNotProcess]      BIT           CONSTRAINT [DF_NonPCBBermLog_DoNotProcess] DEFAULT ((0)) NULL,
    [CertNumber]        VARCHAR (50)  NULL,
    [ReceivedDate]      DATETIME      NULL,
    [NotShipped]        BIT           CONSTRAINT [DF_NonPCBBermLog_NotShipped] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_NonBermLog] PRIMARY KEY CLUSTERED ([BermLogId] ASC)
);

