CREATE TABLE [dbo].[PCBBermACS] (
    [Id]               INT           IDENTITY (1, 1) NOT NULL,
    [Barcode]          VARCHAR (50)  NULL,
    [SerialNumber]     VARCHAR (50)  NULL,
    [Comments]         VARCHAR (500) NULL,
    [KVA]              VARCHAR (50)  NULL,
    [AMPS]             VARCHAR (50)  NULL,
    [WEIGHT]           VARCHAR (50)  NULL,
    [Impedance]        VARCHAR (50)  NULL,
    [JOB_TYPE]         VARCHAR (50)  NULL,
    [LocationDetail]   VARCHAR (150) NULL,
    [PrimaryVoltage]   VARCHAR (50)  NULL,
    [SecondaryVoltage] VARCHAR (50)  NULL,
    [Manufacturer]     VARCHAR (50)  NULL,
    [TAPS]             VARCHAR (50)  NULL,
    [TYPE]             VARCHAR (50)  NULL,
    [LOOP_RAD]         VARCHAR (50)  NULL,
    [FRONT]            VARCHAR (50)  NULL,
    [EOK]              VARCHAR (3)   NULL,
    [Year]             VARCHAR (50)  NULL,
    [TankType]         VARCHAR (50)  NULL,
    [Repaired]         VARCHAR (50)  NULL,
    [CustomerNumber]   VARCHAR (50)  NULL,
    [PickUpDate]       DATETIME      NULL,
    [Fuse]             VARCHAR (50)  NULL,
    [Condition]        VARCHAR (50)  NULL,
    [Volts]            VARCHAR (50)  NULL,
    [W_PANEL_WITH]     VARCHAR (5)   NULL,
    [PANEL_SER]        VARCHAR (50)  NULL,
    [PrimaryWinding]   VARCHAR (50)  NULL,
    [SecondaryWinding] VARCHAR (50)  NULL,
    [datestamp]        DATETIME      CONSTRAINT [DF_PCBBermACS_datestamp] DEFAULT (getdate()) NULL,
    [Description]      VARCHAR (150) NULL,
    [Rec_Date]         DATE          NULL
);

