CREATE TABLE [dbo].[PCBBermLog] (
    [BermLogId]         INT           IDENTITY (1, 1) NOT NULL,
    [BatchId]           INT           NULL,
    [Barcode]           VARCHAR (50)  NULL,
    [SerialNumber]      VARCHAR (50)  NULL,
    [InitialWeight]     FLOAT (53)    NULL,
    [CarcassWeight]     FLOAT (53)    NULL,
    [Gallons]           FLOAT (53)    NULL,
    [OilTankId]         INT           NULL,
    [PPM]               FLOAT (53)    NULL,
    [DateStamp]         DATETIME      NULL,
    [LastUpdated]       DATETIME      NULL,
    [SendTo]            VARCHAR (5)   NULL,
    [ContinuationGroup] INT           NULL,
    [PCBSampleId]       INT           NULL,
    [Drained]           VARCHAR (25)  CONSTRAINT [[dbo]].[PCBBermLog]]DrainedDefault] DEFAULT ('Not Drained') NULL,
    [DateCompleted]     DATETIME      NULL,
    [ASD]               DATETIME      NULL,
    [SequenceNumber]    VARCHAR (25)  NULL,
    [PCBItemTypeID]     INT           NULL,
    [PumpOutDate]       DATE          NULL,
    [ManualEntry]       BIT           CONSTRAINT [[dbo]].[PCBBermLog]]ManualEntryDefault] DEFAULT ((0)) NULL,
    [ContinuationId]    INT           NULL,
    [KVA]               FLOAT (53)    CONSTRAINT [[dbo]].[PCBBermLog]]KVADefault] DEFAULT ((0)) NULL,
    [PickUpDate]        DATETIME      NULL,
    [CustomerNumber]    VARCHAR (50)  NULL,
    [Description]       VARCHAR (150) NULL,
    [acsinfo]           BIT           CONSTRAINT [[dbo]].[PCBBermLog]]acsinfoDefault] DEFAULT ((0)) NULL,
    [OilContinuationId] INT           NULL,
    [DoNotProcess]      BIT           CONSTRAINT [[dbo]].[PCBBermLog]]DoNotProcessDefault] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BermLog] PRIMARY KEY CLUSTERED ([BermLogId] ASC)
);

