CREATE TABLE [dbo].[StoredValues] (
    [ID]                      INT           IDENTITY (1, 1) NOT NULL,
    [Description]             VARCHAR (150) NULL,
    [Value]                   VARCHAR (50)  NULL,
    [Status]                  VARCHAR (1)   CONSTRAINT [DF_INVStoredValues_Status] DEFAULT ('A') NULL,
    [ForUseIn]                VARCHAR (50)  NULL,
    [InventoryLocation]       INT           NULL,
    [Manufacturer]            INT           NULL,
    [Taps]                    INT           NULL,
    [PrimaryVoltage]          INT           NULL,
    [SecondaryVoltage]        INT           NULL,
    [KVA]                     INT           NULL,
    [AMPS]                    INT           NULL,
    [EOK]                     INT           NULL,
    [Type]                    INT           NULL,
    [Front]                   INT           NULL,
    [TankType]                INT           NULL,
    [Repaired]                INT           NULL,
    [LoopRadial]              INT           NULL,
    [KVAenabled]              BIT           CONSTRAINT [[dbo]].[StoredValues]]KVAenabledDefault] DEFAULT ((1)) NULL,
    [AMPSenabled]             BIT           CONSTRAINT [[dbo]].[StoredValues]]AMPSenabledDefault] DEFAULT ((1)) NULL,
    [Impenabled]              BIT           CONSTRAINT [[dbo]].[StoredValues]]ImpenabledDefault] DEFAULT ((1)) NULL,
    [TapsEnabled]             BIT           CONSTRAINT [[dbo]].[StoredValues]]TapsEnabledDefault] DEFAULT ((1)) NULL,
    [PrimaryVoltageEnabled]   BIT           CONSTRAINT [[dbo]].[StoredValues]]PrimaryVoltageEnabledDefault] DEFAULT ((1)) NULL,
    [PrimaryWindingEnabled]   BIT           CONSTRAINT [[dbo]].[StoredValues]]PrimaryWindingEnabledDefault] DEFAULT ((1)) NULL,
    [SecondaryVoltageEnabled] BIT           CONSTRAINT [[dbo]].[StoredValues]]SecondaryVoltageEnabledDefault] DEFAULT ((1)) NULL,
    [SecondaryWindingEnabled] BIT           CONSTRAINT [[dbo]].[StoredValues]]SecondaryWindingEnabledDefault] DEFAULT ((1)) NULL,
    [EOKEnabled]              BIT           CONSTRAINT [[dbo]].[StoredValues]]EOKEnabledDefault] DEFAULT ((1)) NULL,
    [TypeEnabled]             BIT           CONSTRAINT [[dbo]].[StoredValues]]TypeEnabledDefault] DEFAULT ((1)) NULL,
    [FrontEnabled]            BIT           CONSTRAINT [[dbo]].[StoredValues]]FrontEnabledDefault] DEFAULT ((1)) NULL,
    [TankTypeEnabled]         BIT           CONSTRAINT [[dbo]].[StoredValues]]TankTypeEnabledDefault] DEFAULT ((1)) NULL,
    [RepairedEnabled]         BIT           CONSTRAINT [[dbo]].[StoredValues]]RepairedEnabledDefault] DEFAULT ((1)) NULL,
    [LoopRadialEnabled]       BIT           CONSTRAINT [[dbo]].[StoredValues]]LoopRadialEnabledDefault] DEFAULT ((1)) NULL
);

