CREATE TABLE [dbo].[TrailerRequests] (
    [TrailerLogID]      INT      IDENTITY (1, 1) NOT NULL,
    [BayId]             INT      NULL,
    [TrailerId]         INT      NULL,
    [RequestedDate]     DATETIME NULL,
    [DateStamp]         DATETIME NULL,
    [UID]               INT      NULL,
    [Status]            BIT      CONSTRAINT [DF_TrailerRequests_Status] DEFAULT ((1)) NULL,
    [RequestRemoved]    DATETIME NULL,
    [RemovedBy]         INT      NULL,
    [TrailerReady]      DATETIME NULL,
    [TrailerReadyBy]    INT      NULL,
    [CancDurUnload]     BIT      CONSTRAINT [DF_TrailerRequests_CancDurUnload] DEFAULT ((0)) NULL,
    [CancAftUnload]     BIT      CONSTRAINT [DF_TrailerRequests_CancAftUnload] DEFAULT ((0)) NULL,
    [CancBefUnload]     BIT      NULL,
    [BeginUnload]       DATETIME NULL,
    [UnloadBeginBy]     INT      NULL,
    [CompleteUnload]    DATETIME NULL,
    [UnloadCompletedBy] INT      NULL,
    [11]                INT      CONSTRAINT [DF_TrailerRequests_11] DEFAULT ((0)) NULL,
    [12]                INT      CONSTRAINT [DF_TrailerRequests_12] DEFAULT ((0)) NULL,
    [13]                INT      CONSTRAINT [DF_TrailerRequests_13] DEFAULT ((0)) NULL,
    [51]                INT      CONSTRAINT [DF_TrailerRequests_51] DEFAULT ((0)) NULL,
    [52]                INT      CONSTRAINT [DF_TrailerRequests_52] DEFAULT ((0)) NULL,
    [53]                INT      CONSTRAINT [DF_TrailerRequests_53] DEFAULT ((0)) NULL,
    [54]                INT      CONSTRAINT [DF_TrailerRequests_54] DEFAULT ((0)) NULL,
    [61]                INT      CONSTRAINT [DF_TrailerRequests_61] DEFAULT ((0)) NULL,
    [62]                INT      CONSTRAINT [DF_TrailerRequests_62] DEFAULT ((0)) NULL,
    [64]                INT      CONSTRAINT [DF_TrailerRequests_64] DEFAULT ((0)) NULL,
    [71]                INT      CONSTRAINT [DF_TrailerRequests_71] DEFAULT ((0)) NULL,
    [73]                INT      CONSTRAINT [DF_TrailerRequests_73] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TrailerRequests] PRIMARY KEY CLUSTERED ([TrailerLogID] ASC)
);

