CREATE TABLE [dbo].[TransferredUnits] (
    [TransferredUnitId]  INT           IDENTITY (1, 1) NOT NULL,
    [Job Type]           VARCHAR (15)  NULL,
    [Barcode]            VARCHAR (25)  NULL,
    [UID]                INT           NULL,
    [KVA]                VARCHAR (10)  NULL,
    [RECEIVED DATE]      DATE          NULL,
    [PRI_VOLT]           VARCHAR (20)  NULL,
    [SEC_VOLT]           VARCHAR (20)  NULL,
    [TEST DATE]          DATE          NULL,
    [Paint DATE]         DATE          NULL,
    [Serial Number]      VARCHAR (50)  NULL,
    [Customer Number]    VARCHAR (10)  NULL,
    [Location]           INT           NULL,
    [Type]               VARCHAR (15)  NULL,
    [Volts]              VARCHAR (10)  NULL,
    [AMPS]               VARCHAR (15)  NULL,
    [Promise Date]       DATE          NULL,
    [Ship Date]          DATE          NULL,
    [uShipDate]          DATE          NULL,
    [uPaintDate]         DATE          NULL,
    [uTestDate]          DATE          NULL,
    [EstApproved]        DATE          NULL,
    [Dept Code]          VARCHAR (5)   NULL,
    [Est First]          VARCHAR (5)   NULL,
    [MFGR]               VARCHAR (50)  NULL,
    [TAPS]               VARCHAR (5)   NULL,
    [WEIGHT1]            VARCHAR (15)  NULL,
    [W_PANEL_WITH]       VARCHAR (5)   NULL,
    [PANEL_SER]          VARCHAR (25)  NULL,
    [LOOP_RAD]           VARCHAR (15)  NULL,
    [IMP]                VARCHAR (15)  NULL,
    [DESC]               VARCHAR (50)  NULL,
    [BUSH_CNT]           VARCHAR (15)  NULL,
    [J_OTIME_FLAG]       VARCHAR (5)   NULL,
    [DateStamp]          DATETIME      CONSTRAINT [DF_TransferredUnits_DateStamp] DEFAULT (getdate()) NULL,
    [UnitStatus]         BIT           CONSTRAINT [DF_TransferredUnits_UnitStatus] DEFAULT ((1)) NULL,
    [Decom Date]         DATETIME      NULL,
    [EstComplete]        DATETIME      NULL,
    [uDecomDate]         DATETIME      NULL,
    [J_CUST_PO_]         VARCHAR (25)  NULL,
    [ushopdate]          DATETIME      NULL,
    [uwelddate]          DATETIME      NULL,
    [uovendate]          DATETIME      NULL,
    [upowdercoat]        DATETIME      NULL,
    [J_JOB_TOTAL]        FLOAT (53)    NULL,
    [BUDGET_AMT]         FLOAT (53)    NULL,
    [J_PO_REL_NBR]       VARCHAR (50)  NULL,
    [Comment]            VARCHAR (150) NULL,
    [UnitTranferredTo]   VARCHAR (5)   NULL,
    [TransferDate]       DATETIME      NULL,
    [UnitTranferredFrom] VARCHAR (5)   NULL,
    [TransRecDate]       DATETIME      NULL,
    CONSTRAINT [PK_TransferredUnits] PRIMARY KEY CLUSTERED ([TransferredUnitId] ASC)
);

