CREATE TABLE [dbo].[Users] (
    [ID]                      INT           IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME]               VARCHAR (50)  NULL,
    [LASTNAME]                VARCHAR (50)  NULL,
    [USERID]                  VARCHAR (50)  NULL,
    [PASSWORD]                VARCHAR (150) NULL,
    [LASTLOGIN]               DATETIME      CONSTRAINT [DF_USERS_LASTLOGIN] DEFAULT ('1/1/1900 12:00:00 AM') NULL,
    [STATUS]                  VARCHAR (2)   CONSTRAINT [DF_InvUsers_STATUS] DEFAULT ('A') NULL,
    [Location]                INT           NULL,
    [ReadOnly]                BIT           CONSTRAINT [[dbo]].[Users]]ReadOnlyDefault] DEFAULT ((0)) NULL,
    [Paint]                   BIT           CONSTRAINT [[dbo]].[Users]]PaintDefault] DEFAULT ((0)) NULL,
    [Decom]                   BIT           CONSTRAINT [[dbo]].[Users]]DecomDefault] DEFAULT ((0)) NULL,
    [IsAdmin]                 BIT           CONSTRAINT [[dbo]].[Users]]IsAdminDefault] DEFAULT ((0)) NULL,
    [MaintenanceRequests]     BIT           CONSTRAINT [[dbo]].[Users]]MaintenanceRequestsDefault] DEFAULT ((0)) NULL,
    [MaintenanceRequestAdmin] BIT           CONSTRAINT [[dbo]].[Users]]MaintenanceRequestAdminDefault] DEFAULT ((0)) NULL,
    [MaintTechnician]         BIT           CONSTRAINT [[dbo]].[Users]]MaintTechnicianDefault] DEFAULT ((0)) NULL,
    [PCBLab]                  BIT           CONSTRAINT [[dbo]].[Users]]PCBLabDefault] DEFAULT ((0)) NULL,
    [InternalLabResults]      BIT           CONSTRAINT [[dbo]].[Users]]InternalLabResultsDefault] DEFAULT ((0)) NULL,
    [OilLog]                  BIT           CONSTRAINT [[dbo]].[Users]]OilLogDefault] DEFAULT ((0)) NULL,
    [FieldInvAdmin]           BIT           CONSTRAINT [[dbo]].[Users]]FieldInvAdminDefault] DEFAULT ((0)) NULL,
    [PCBPRocessing]           BIT           CONSTRAINT [[dbo]].[Users]]PCBPRocessingDefault] DEFAULT ((0)) NULL,
    [FieldService]            BIT           CONSTRAINT [[dbo]].[Users]]FieldServiceDefault] DEFAULT ((0)) NULL,
    [PCBProcessOffice]        BIT           CONSTRAINT [[dbo]].[Users]]PCBProcessOfficeDefault] DEFAULT ((0)) NULL,
    [QADock]                  BIT           CONSTRAINT [DF_Users_QADock] DEFAULT ((0)) NULL,
    [QAAdmin]                 BIT           CONSTRAINT [DF_Users_QAAdmin] DEFAULT ((0)) NULL,
    [QAPaint]                 BIT           CONSTRAINT [DF_Users_QAPaint] DEFAULT ((0)) NULL,
    [QAPAd]                   BIT           CONSTRAINT [DF_Users_QAPAd] DEFAULT ((0)) NULL,
    [QAPole]                  BIT           CONSTRAINT [DF_Users_QAPole] DEFAULT ((0)) NULL,
    [QARecloser]              BIT           CONSTRAINT [DF_Users_QARecloser] DEFAULT ((0)) NULL,
    [Backlog]                 BIT           CONSTRAINT [DF_Users_Backlog] DEFAULT ((0)) NULL,
    [QARegulator]             BIT           CONSTRAINT [DF_Users_QARegulator] DEFAULT ((0)) NULL,
    [EmailAddress]            VARCHAR (150) NULL,
    [SalesPortal]             BIT           CONSTRAINT [DF_Users_SalesPortal] DEFAULT ((0)) NULL,
    [MetricsAdmin]            BIT           CONSTRAINT [DF_Users_MetricsAdmin] DEFAULT ((0)) NULL,
    [MetricsUser]             BIT           CONSTRAINT [DF_Users_MetricsUser] DEFAULT ((0)) NULL,
    [QAReceived]              BIT           CONSTRAINT [DF_Users_QAReceived] DEFAULT ((0)) NULL,
    [Backlogadmin]            BIT           CONSTRAINT [DF_Users_Backlogadmin] DEFAULT ((0)) NULL,
    [Specbookuser]            BIT           CONSTRAINT [DF_Users_Specbookuser] DEFAULT ((0)) NULL,
    [SpecBookAdmin]           BIT           CONSTRAINT [DF_Users_SpecBookADmin] DEFAULT ((0)) NULL,
    [QASupport]               BIT           CONSTRAINT [DF_Users_QASupport] DEFAULT ((0)) NULL,
    [DecomLogAdmin]           BIT           CONSTRAINT [DF_Users_DecomLogAdmin] DEFAULT ((0)) NULL,
    [DecomLogUser]            BIT           CONSTRAINT [DF_Users_DecomLogUser] DEFAULT ((0)) NULL,
    [PushLog]                 BIT           CONSTRAINT [DF_Users_PushLog] DEFAULT ((0)) NULL,
    [DecomLog]                BIT           CONSTRAINT [DF_Users_DecomLog] DEFAULT ((0)) NULL,
    [PackageLog]              BIT           CONSTRAINT [DF_Users_PackageLog] DEFAULT ((0)) NULL,
    [ContainerLog]            BIT           CONSTRAINT [DF_Users_ContainerLog] DEFAULT ((0)) NULL,
    [DecomHistory]            BIT           CONSTRAINT [DF_Users_DecomHistory] DEFAULT ((0)) NULL,
    [CheckInLog]              BIT           CONSTRAINT [DF_Users_CheckInLog] DEFAULT ((0)) NULL,
    [whapco]                  BIT           CONSTRAINT [DF_Users_whapco] DEFAULT ((0)) NULL,
    [whmpco]                  BIT           CONSTRAINT [DF_Users_whmpco] DEFAULT ((0)) NULL,
    [TechRequests]            BIT           CONSTRAINT [DF_Users_TechRequests] DEFAULT ((0)) NULL,
    [TechRequestAdmin]        BIT           CONSTRAINT [DF_Users_TechRequestAdmin] DEFAULT ((0)) NULL,
    [TechTechnician]          BIT           CONSTRAINT [DF_Users_TechTechnician] DEFAULT ((0)) NULL,
    [DashboardAdmin]          BIT           CONSTRAINT [DF_Users_DashboardAdmin] DEFAULT ((0)) NULL,
    [DashboardUser]           BIT           CONSTRAINT [DF_Users_DashboardUser] DEFAULT ((0)) NULL,
    [MapAdmin]                BIT           CONSTRAINT [DF_Users_MapAdmin] DEFAULT ((0)) NULL,
    [MapUser]                 BIT           CONSTRAINT [DF_Users_MapUser] DEFAULT ((0)) NULL,
    [DragonLogAdmin]          BIT           CONSTRAINT [DF_Users_DragonLogAdmin] DEFAULT ((0)) NULL,
    [DragonLogUser]           BIT           CONSTRAINT [DF_Users_DragonLogUser] DEFAULT ((0)) NULL,
    [ShippingLogAdmin]        BIT           CONSTRAINT [DF_Users_ShippingLogAdmin] DEFAULT ((0)) NULL,
    [ShippingLogUser]         BIT           CONSTRAINT [DF_Users_ShippingLogUser] DEFAULT ((0)) NULL,
    [TrailerAdmin]            BIT           CONSTRAINT [DF_Users_TrailerAdmin] DEFAULT ((0)) NULL,
    [TrailerInProc]           BIT           CONSTRAINT [DF_Users_TrailerInProc] DEFAULT ((0)) NULL,
    [TrailerRequest]          BIT           CONSTRAINT [DF_Users_TrailerRequest] DEFAULT ((0)) NULL,
    [IsIRAdmin]               BIT           DEFAULT ((0)) NULL,
    [IsEnvChklstAdmin]        BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_Users_UserID_Status]
    ON [dbo].[Users]([USERID] ASC, [STATUS] ASC);

